# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f25763754ccd24df777bb526016986b5fb6a70ccda6a90944232daa253f9908bd669d275f3ec7971e20afb09c8beeb7dce7e7fb5ee70c51cd5e0f2add2590da

test:
  secret_key_base: e54cfa2b422ae28fe2a6632a4bb0be052b861ec1b6db274d7739fca9bc0cb35852cd3966b4de64df545e5a5cd3e553d249462fbdff81e9ca74e54f937872f089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
